---
- hosts: all
  gather_facts: true

  tasks:
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Install python3-dev & python3-pip
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - python3-dev 
        - python3-pip

    - name: Install spidev &  mfrc522 & soco
      pip:
       name: 
         - spidev
         - mfrc522
         - soco
       executable: pip3
      tags: [dependencies]

  roles:
    - {role: deploy, tags: [deploy]}
    - {role: geerlingguy.supervisor, tags: [supervisor]}
    - {role: raspberry-config, tags: [config]}


